Alpine support
kingscode/laravel-api-starter pull request #14
Opened 2021-10-29 12:01 UTC by DennisLammers

2021-11-01 08:55 UTC, ibovangeffen submitted a review, later dismissed

2021-11-01 12:48 UTC, pretendings requested changes
Dit werkt toch nog niet helemaal lekker met die $user en make commando's vanuit de bash?

2021-11-02 07:53 UTC, roelgonzalez commented
Ik zou ook zeker xdebug missen in deze configuratie, ik gebruik dat dagelijks.

2021-11-15 07:50 UTC, DennisLammers commented
> Dit werkt toch nog niet helemaal lekker met die $user en make commando's vanuit de bash?

Dit is opgelost met deze update!

2021-11-15 07:50 UTC, DennisLammers commented
@roelgonzalez 
> Ik zou ook zeker xdebug missen in deze configuratie, ik gebruik dat dagelijks.
Dit zit er nu ook in, straks ff samen testen.

2021-11-15 15:01 UTC, roelgonzalez commented
Getest en werkt! Nice!

2021-11-15 15:02 UTC, roelgonzalez approved these changes

2021-11-16 07:23 UTC, jjcr approved these changes

2021-11-16 07:34 UTC, pretendings approved these changes

2021-11-16 07:46 UTC, merged